from django.conf import settings

from rest_framework.permissions import BasePermission


class AllRequestsDenied(BasePermission):
    """
    Deny all incoming requests.
    """
    def has_permission(self, request, view):
        # '/api/' is an autogenerated view that the frontend uses
        # to see all the endpoints offered by our API.
        # If the request is for '/api/' and Django is in DEBUG mode
        # we'll allow access to this endpoint
        if request._request.path == '/api/' and settings.DEBUG:
            return True
        else:
            return False
